# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    steps:
    - checkout: self
    - task: DockerCompose@1
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'AzureStudentConnection'
        azureContainerRegistry: '{"loginServer":"shareit.azurecr.io", "id" : "/subscriptions/0639a79f-74fa-4426-a9aa-776749dca8cd/resourceGroups/ShareIt/providers/Microsoft.ContainerRegistry/registries/ShareIt"}'
        dockerComposeFile: '**/docker-compose.yml'
        projectName: 'shareit-be'
        action: 'Build services'
        includeLatestTag: true
    - task: DockerCompose@1
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'AzureStudentConnection'
        azureContainerRegistry: '{"loginServer":"shareit.azurecr.io", "id" : "/subscriptions/0639a79f-74fa-4426-a9aa-776749dca8cd/resourceGroups/ShareIt/providers/Microsoft.ContainerRegistry/registries/ShareIt"}'
        dockerComposeFile: '**/docker-compose.yml'
        projectName: 'shareit-be'
        action: 'Push services'
        includeLatestTag: true
